### ISSUE TITLE
Resolve linking problem

### ISSUE THREAD

**Issue by VMaksimN** [VMaksimN/imager#15]
Prevent code duplication, colors.h is included more than once

**Comment by lasest** [comment]
It has `#pragma once` directive, the linker would only include it once anyway, so what's the problem?

**Comment by lasest** [comment]
Variable was declared in header file. Defenition was moved to .cpp file. Solved
Links:
https://docs.microsoft.com/en-us/cpp/cpp/extern-cpp?view=vs-2019
https://stackoverflow.com/questions/249701/why-arent-my-compile-guards-preventing-multiple-definition-inclusions
